/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVultrShopHealthRouteImport } from './routes/api/vultr-shop/health'
import { Route as ApiVultrShopBreakRouteImport } from './routes/api/vultr-shop/break'
import { Route as ApiShopProductsRouteImport } from './routes/api/shop/products'
import { Route as ApiShopHealthRouteImport } from './routes/api/shop/health'
import { Route as ApiShopCheckoutRouteImport } from './routes/api/shop/checkout'
import { Route as ApiShopAdminBreakRouteImport } from './routes/api/shop/admin.break'
import { Route as ApiPublicMaydayVoiceResponseRouteImport } from './routes/api/public/mayday/voice-response'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVultrShopHealthRoute = ApiVultrShopHealthRouteImport.update({
  id: '/api/vultr-shop/health',
  path: '/api/vultr-shop/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVultrShopBreakRoute = ApiVultrShopBreakRouteImport.update({
  id: '/api/vultr-shop/break',
  path: '/api/vultr-shop/break',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopProductsRoute = ApiShopProductsRouteImport.update({
  id: '/api/shop/products',
  path: '/api/shop/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopHealthRoute = ApiShopHealthRouteImport.update({
  id: '/api/shop/health',
  path: '/api/shop/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopCheckoutRoute = ApiShopCheckoutRouteImport.update({
  id: '/api/shop/checkout',
  path: '/api/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopAdminBreakRoute = ApiShopAdminBreakRouteImport.update({
  id: '/api/shop/admin/break',
  path: '/api/shop/admin/break',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaydayVoiceResponseRoute =
  ApiPublicMaydayVoiceResponseRouteImport.update({
    id: '/api/public/mayday/voice-response',
    path: '/api/public/mayday/voice-response',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/health': typeof ApiShopHealthRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/vultr-shop/break': typeof ApiVultrShopBreakRoute
  '/api/vultr-shop/health': typeof ApiVultrShopHealthRoute
  '/api/public/mayday/voice-response': typeof ApiPublicMaydayVoiceResponseRoute
  '/api/shop/admin/break': typeof ApiShopAdminBreakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/health': typeof ApiShopHealthRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/vultr-shop/break': typeof ApiVultrShopBreakRoute
  '/api/vultr-shop/health': typeof ApiVultrShopHealthRoute
  '/api/public/mayday/voice-response': typeof ApiPublicMaydayVoiceResponseRoute
  '/api/shop/admin/break': typeof ApiShopAdminBreakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/health': typeof ApiShopHealthRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/vultr-shop/break': typeof ApiVultrShopBreakRoute
  '/api/vultr-shop/health': typeof ApiVultrShopHealthRoute
  '/api/public/mayday/voice-response': typeof ApiPublicMaydayVoiceResponseRoute
  '/api/shop/admin/break': typeof ApiShopAdminBreakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/api/shop/checkout'
    | '/api/shop/health'
    | '/api/shop/products'
    | '/api/vultr-shop/break'
    | '/api/vultr-shop/health'
    | '/api/public/mayday/voice-response'
    | '/api/shop/admin/break'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop'
    | '/api/shop/checkout'
    | '/api/shop/health'
    | '/api/shop/products'
    | '/api/vultr-shop/break'
    | '/api/vultr-shop/health'
    | '/api/public/mayday/voice-response'
    | '/api/shop/admin/break'
  id:
    | '__root__'
    | '/'
    | '/shop'
    | '/api/shop/checkout'
    | '/api/shop/health'
    | '/api/shop/products'
    | '/api/vultr-shop/break'
    | '/api/vultr-shop/health'
    | '/api/public/mayday/voice-response'
    | '/api/shop/admin/break'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRoute
  ApiShopCheckoutRoute: typeof ApiShopCheckoutRoute
  ApiShopHealthRoute: typeof ApiShopHealthRoute
  ApiShopProductsRoute: typeof ApiShopProductsRoute
  ApiVultrShopBreakRoute: typeof ApiVultrShopBreakRoute
  ApiVultrShopHealthRoute: typeof ApiVultrShopHealthRoute
  ApiPublicMaydayVoiceResponseRoute: typeof ApiPublicMaydayVoiceResponseRoute
  ApiShopAdminBreakRoute: typeof ApiShopAdminBreakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vultr-shop/health': {
      id: '/api/vultr-shop/health'
      path: '/api/vultr-shop/health'
      fullPath: '/api/vultr-shop/health'
      preLoaderRoute: typeof ApiVultrShopHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vultr-shop/break': {
      id: '/api/vultr-shop/break'
      path: '/api/vultr-shop/break'
      fullPath: '/api/vultr-shop/break'
      preLoaderRoute: typeof ApiVultrShopBreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/products': {
      id: '/api/shop/products'
      path: '/api/shop/products'
      fullPath: '/api/shop/products'
      preLoaderRoute: typeof ApiShopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/health': {
      id: '/api/shop/health'
      path: '/api/shop/health'
      fullPath: '/api/shop/health'
      preLoaderRoute: typeof ApiShopHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/checkout': {
      id: '/api/shop/checkout'
      path: '/api/shop/checkout'
      fullPath: '/api/shop/checkout'
      preLoaderRoute: typeof ApiShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/admin/break': {
      id: '/api/shop/admin/break'
      path: '/api/shop/admin/break'
      fullPath: '/api/shop/admin/break'
      preLoaderRoute: typeof ApiShopAdminBreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/voice-response': {
      id: '/api/public/mayday/voice-response'
      path: '/api/public/mayday/voice-response'
      fullPath: '/api/public/mayday/voice-response'
      preLoaderRoute: typeof ApiPublicMaydayVoiceResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRoute,
  ApiShopCheckoutRoute: ApiShopCheckoutRoute,
  ApiShopHealthRoute: ApiShopHealthRoute,
  ApiShopProductsRoute: ApiShopProductsRoute,
  ApiVultrShopBreakRoute: ApiVultrShopBreakRoute,
  ApiVultrShopHealthRoute: ApiVultrShopHealthRoute,
  ApiPublicMaydayVoiceResponseRoute: ApiPublicMaydayVoiceResponseRoute,
  ApiShopAdminBreakRoute: ApiShopAdminBreakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
