/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVultrShopHealthRouteImport } from './routes/api/vultr-shop/health'
import { Route as ApiVultrShopBreakRouteImport } from './routes/api/vultr-shop/break'
import { Route as ApiShopProductsRouteImport } from './routes/api/shop/products'
import { Route as ApiShopHealthRouteImport } from './routes/api/shop/health'
import { Route as ApiShopCheckoutRouteImport } from './routes/api/shop/checkout'
import { Route as ApiMaydayPlaceCallRouteImport } from './routes/api/mayday/place-call'
import { Route as ApiMaydayBrainTestRouteImport } from './routes/api/mayday/brain-test'
import { Route as ApiShopAdminBreakRouteImport } from './routes/api/shop/admin.break'
import { Route as ApiPublicMaydayVoiceResponseRouteImport } from './routes/api/public/mayday/voice-response'
import { Route as ApiPublicMaydayTtsRouteImport } from './routes/api/public/mayday/tts'
import { Route as ApiPublicMaydayStatusRouteImport } from './routes/api/public/mayday/status'
import { Route as ApiPublicMaydaySelftestRouteImport } from './routes/api/public/mayday/selftest'
import { Route as ApiPublicMaydayRecordingRouteImport } from './routes/api/public/mayday/recording'
import { Route as ApiPublicMaydayHoldRouteImport } from './routes/api/public/mayday/hold'
import { Route as ApiPublicMaydayGatherTestRouteImport } from './routes/api/public/mayday/gather-test'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVultrShopHealthRoute = ApiVultrShopHealthRouteImport.update({
  id: '/api/vultr-shop/health',
  path: '/api/vultr-shop/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVultrShopBreakRoute = ApiVultrShopBreakRouteImport.update({
  id: '/api/vultr-shop/break',
  path: '/api/vultr-shop/break',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopProductsRoute = ApiShopProductsRouteImport.update({
  id: '/api/shop/products',
  path: '/api/shop/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopHealthRoute = ApiShopHealthRouteImport.update({
  id: '/api/shop/health',
  path: '/api/shop/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopCheckoutRoute = ApiShopCheckoutRouteImport.update({
  id: '/api/shop/checkout',
  path: '/api/shop/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaydayPlaceCallRoute = ApiMaydayPlaceCallRouteImport.update({
  id: '/api/mayday/place-call',
  path: '/api/mayday/place-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMaydayBrainTestRoute = ApiMaydayBrainTestRouteImport.update({
  id: '/api/mayday/brain-test',
  path: '/api/mayday/brain-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopAdminBreakRoute = ApiShopAdminBreakRouteImport.update({
  id: '/api/shop/admin/break',
  path: '/api/shop/admin/break',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaydayVoiceResponseRoute =
  ApiPublicMaydayVoiceResponseRouteImport.update({
    id: '/api/public/mayday/voice-response',
    path: '/api/public/mayday/voice-response',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMaydayTtsRoute = ApiPublicMaydayTtsRouteImport.update({
  id: '/api/public/mayday/tts',
  path: '/api/public/mayday/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaydayStatusRoute = ApiPublicMaydayStatusRouteImport.update({
  id: '/api/public/mayday/status',
  path: '/api/public/mayday/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaydaySelftestRoute = ApiPublicMaydaySelftestRouteImport.update({
  id: '/api/public/mayday/selftest',
  path: '/api/public/mayday/selftest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaydayRecordingRoute =
  ApiPublicMaydayRecordingRouteImport.update({
    id: '/api/public/mayday/recording',
    path: '/api/public/mayday/recording',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMaydayHoldRoute = ApiPublicMaydayHoldRouteImport.update({
  id: '/api/public/mayday/hold',
  path: '/api/public/mayday/hold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaydayGatherTestRoute =
  ApiPublicMaydayGatherTestRouteImport.update({
    id: '/api/public/mayday/gather-test',
    path: '/api/public/mayday/gather-test',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/mayday/brain-test': typeof ApiMaydayBrainTestRoute
  '/api/mayday/place-call': typeof ApiMaydayPlaceCallRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/health': typeof ApiShopHealthRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/vultr-shop/break': typeof ApiVultrShopBreakRoute
  '/api/vultr-shop/health': typeof ApiVultrShopHealthRoute
  '/api/public/mayday/gather-test': typeof ApiPublicMaydayGatherTestRoute
  '/api/public/mayday/hold': typeof ApiPublicMaydayHoldRoute
  '/api/public/mayday/recording': typeof ApiPublicMaydayRecordingRoute
  '/api/public/mayday/selftest': typeof ApiPublicMaydaySelftestRoute
  '/api/public/mayday/status': typeof ApiPublicMaydayStatusRoute
  '/api/public/mayday/tts': typeof ApiPublicMaydayTtsRoute
  '/api/public/mayday/voice-response': typeof ApiPublicMaydayVoiceResponseRoute
  '/api/shop/admin/break': typeof ApiShopAdminBreakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/mayday/brain-test': typeof ApiMaydayBrainTestRoute
  '/api/mayday/place-call': typeof ApiMaydayPlaceCallRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/health': typeof ApiShopHealthRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/vultr-shop/break': typeof ApiVultrShopBreakRoute
  '/api/vultr-shop/health': typeof ApiVultrShopHealthRoute
  '/api/public/mayday/gather-test': typeof ApiPublicMaydayGatherTestRoute
  '/api/public/mayday/hold': typeof ApiPublicMaydayHoldRoute
  '/api/public/mayday/recording': typeof ApiPublicMaydayRecordingRoute
  '/api/public/mayday/selftest': typeof ApiPublicMaydaySelftestRoute
  '/api/public/mayday/status': typeof ApiPublicMaydayStatusRoute
  '/api/public/mayday/tts': typeof ApiPublicMaydayTtsRoute
  '/api/public/mayday/voice-response': typeof ApiPublicMaydayVoiceResponseRoute
  '/api/shop/admin/break': typeof ApiShopAdminBreakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/api/mayday/brain-test': typeof ApiMaydayBrainTestRoute
  '/api/mayday/place-call': typeof ApiMaydayPlaceCallRoute
  '/api/shop/checkout': typeof ApiShopCheckoutRoute
  '/api/shop/health': typeof ApiShopHealthRoute
  '/api/shop/products': typeof ApiShopProductsRoute
  '/api/vultr-shop/break': typeof ApiVultrShopBreakRoute
  '/api/vultr-shop/health': typeof ApiVultrShopHealthRoute
  '/api/public/mayday/gather-test': typeof ApiPublicMaydayGatherTestRoute
  '/api/public/mayday/hold': typeof ApiPublicMaydayHoldRoute
  '/api/public/mayday/recording': typeof ApiPublicMaydayRecordingRoute
  '/api/public/mayday/selftest': typeof ApiPublicMaydaySelftestRoute
  '/api/public/mayday/status': typeof ApiPublicMaydayStatusRoute
  '/api/public/mayday/tts': typeof ApiPublicMaydayTtsRoute
  '/api/public/mayday/voice-response': typeof ApiPublicMaydayVoiceResponseRoute
  '/api/shop/admin/break': typeof ApiShopAdminBreakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/api/mayday/brain-test'
    | '/api/mayday/place-call'
    | '/api/shop/checkout'
    | '/api/shop/health'
    | '/api/shop/products'
    | '/api/vultr-shop/break'
    | '/api/vultr-shop/health'
    | '/api/public/mayday/gather-test'
    | '/api/public/mayday/hold'
    | '/api/public/mayday/recording'
    | '/api/public/mayday/selftest'
    | '/api/public/mayday/status'
    | '/api/public/mayday/tts'
    | '/api/public/mayday/voice-response'
    | '/api/shop/admin/break'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop'
    | '/api/mayday/brain-test'
    | '/api/mayday/place-call'
    | '/api/shop/checkout'
    | '/api/shop/health'
    | '/api/shop/products'
    | '/api/vultr-shop/break'
    | '/api/vultr-shop/health'
    | '/api/public/mayday/gather-test'
    | '/api/public/mayday/hold'
    | '/api/public/mayday/recording'
    | '/api/public/mayday/selftest'
    | '/api/public/mayday/status'
    | '/api/public/mayday/tts'
    | '/api/public/mayday/voice-response'
    | '/api/shop/admin/break'
  id:
    | '__root__'
    | '/'
    | '/shop'
    | '/api/mayday/brain-test'
    | '/api/mayday/place-call'
    | '/api/shop/checkout'
    | '/api/shop/health'
    | '/api/shop/products'
    | '/api/vultr-shop/break'
    | '/api/vultr-shop/health'
    | '/api/public/mayday/gather-test'
    | '/api/public/mayday/hold'
    | '/api/public/mayday/recording'
    | '/api/public/mayday/selftest'
    | '/api/public/mayday/status'
    | '/api/public/mayday/tts'
    | '/api/public/mayday/voice-response'
    | '/api/shop/admin/break'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRoute
  ApiMaydayBrainTestRoute: typeof ApiMaydayBrainTestRoute
  ApiMaydayPlaceCallRoute: typeof ApiMaydayPlaceCallRoute
  ApiShopCheckoutRoute: typeof ApiShopCheckoutRoute
  ApiShopHealthRoute: typeof ApiShopHealthRoute
  ApiShopProductsRoute: typeof ApiShopProductsRoute
  ApiVultrShopBreakRoute: typeof ApiVultrShopBreakRoute
  ApiVultrShopHealthRoute: typeof ApiVultrShopHealthRoute
  ApiPublicMaydayGatherTestRoute: typeof ApiPublicMaydayGatherTestRoute
  ApiPublicMaydayHoldRoute: typeof ApiPublicMaydayHoldRoute
  ApiPublicMaydayRecordingRoute: typeof ApiPublicMaydayRecordingRoute
  ApiPublicMaydaySelftestRoute: typeof ApiPublicMaydaySelftestRoute
  ApiPublicMaydayStatusRoute: typeof ApiPublicMaydayStatusRoute
  ApiPublicMaydayTtsRoute: typeof ApiPublicMaydayTtsRoute
  ApiPublicMaydayVoiceResponseRoute: typeof ApiPublicMaydayVoiceResponseRoute
  ApiShopAdminBreakRoute: typeof ApiShopAdminBreakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vultr-shop/health': {
      id: '/api/vultr-shop/health'
      path: '/api/vultr-shop/health'
      fullPath: '/api/vultr-shop/health'
      preLoaderRoute: typeof ApiVultrShopHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vultr-shop/break': {
      id: '/api/vultr-shop/break'
      path: '/api/vultr-shop/break'
      fullPath: '/api/vultr-shop/break'
      preLoaderRoute: typeof ApiVultrShopBreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/products': {
      id: '/api/shop/products'
      path: '/api/shop/products'
      fullPath: '/api/shop/products'
      preLoaderRoute: typeof ApiShopProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/health': {
      id: '/api/shop/health'
      path: '/api/shop/health'
      fullPath: '/api/shop/health'
      preLoaderRoute: typeof ApiShopHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/checkout': {
      id: '/api/shop/checkout'
      path: '/api/shop/checkout'
      fullPath: '/api/shop/checkout'
      preLoaderRoute: typeof ApiShopCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mayday/place-call': {
      id: '/api/mayday/place-call'
      path: '/api/mayday/place-call'
      fullPath: '/api/mayday/place-call'
      preLoaderRoute: typeof ApiMaydayPlaceCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mayday/brain-test': {
      id: '/api/mayday/brain-test'
      path: '/api/mayday/brain-test'
      fullPath: '/api/mayday/brain-test'
      preLoaderRoute: typeof ApiMaydayBrainTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/admin/break': {
      id: '/api/shop/admin/break'
      path: '/api/shop/admin/break'
      fullPath: '/api/shop/admin/break'
      preLoaderRoute: typeof ApiShopAdminBreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/voice-response': {
      id: '/api/public/mayday/voice-response'
      path: '/api/public/mayday/voice-response'
      fullPath: '/api/public/mayday/voice-response'
      preLoaderRoute: typeof ApiPublicMaydayVoiceResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/tts': {
      id: '/api/public/mayday/tts'
      path: '/api/public/mayday/tts'
      fullPath: '/api/public/mayday/tts'
      preLoaderRoute: typeof ApiPublicMaydayTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/status': {
      id: '/api/public/mayday/status'
      path: '/api/public/mayday/status'
      fullPath: '/api/public/mayday/status'
      preLoaderRoute: typeof ApiPublicMaydayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/selftest': {
      id: '/api/public/mayday/selftest'
      path: '/api/public/mayday/selftest'
      fullPath: '/api/public/mayday/selftest'
      preLoaderRoute: typeof ApiPublicMaydaySelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/recording': {
      id: '/api/public/mayday/recording'
      path: '/api/public/mayday/recording'
      fullPath: '/api/public/mayday/recording'
      preLoaderRoute: typeof ApiPublicMaydayRecordingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/hold': {
      id: '/api/public/mayday/hold'
      path: '/api/public/mayday/hold'
      fullPath: '/api/public/mayday/hold'
      preLoaderRoute: typeof ApiPublicMaydayHoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mayday/gather-test': {
      id: '/api/public/mayday/gather-test'
      path: '/api/public/mayday/gather-test'
      fullPath: '/api/public/mayday/gather-test'
      preLoaderRoute: typeof ApiPublicMaydayGatherTestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRoute,
  ApiMaydayBrainTestRoute: ApiMaydayBrainTestRoute,
  ApiMaydayPlaceCallRoute: ApiMaydayPlaceCallRoute,
  ApiShopCheckoutRoute: ApiShopCheckoutRoute,
  ApiShopHealthRoute: ApiShopHealthRoute,
  ApiShopProductsRoute: ApiShopProductsRoute,
  ApiVultrShopBreakRoute: ApiVultrShopBreakRoute,
  ApiVultrShopHealthRoute: ApiVultrShopHealthRoute,
  ApiPublicMaydayGatherTestRoute: ApiPublicMaydayGatherTestRoute,
  ApiPublicMaydayHoldRoute: ApiPublicMaydayHoldRoute,
  ApiPublicMaydayRecordingRoute: ApiPublicMaydayRecordingRoute,
  ApiPublicMaydaySelftestRoute: ApiPublicMaydaySelftestRoute,
  ApiPublicMaydayStatusRoute: ApiPublicMaydayStatusRoute,
  ApiPublicMaydayTtsRoute: ApiPublicMaydayTtsRoute,
  ApiPublicMaydayVoiceResponseRoute: ApiPublicMaydayVoiceResponseRoute,
  ApiShopAdminBreakRoute: ApiShopAdminBreakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
